version: "3.8"
services:
  cache:
    image: redis:6.2-alpine
    container_name: otus_testing_redis
    restart: always
    ports:
      - '6379:6379'
    command:
      - /bin/sh
      - -c
      - "redis-server --requirepass $$REDIS_PASSWORD"
    env_file:
      - .env